#!/bin/sh
. "$(dirname $0)/_/husky.sh"
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  if echo "$changed_files" | grep --quiet "$1" ;
    then eval "$2"
  else
    exit 0
  fi
}

# run `yarn install` if package.json changed
check_run package.json "yarn install"
